steps:
  - label: "Install Dependencies"
    command:
      - "asdf install"
    agents:
      queue: "default"

  - label: "Build"
    command:
      - "npm install"
    agents:
      queue: "default"
